### ISSUE TITLE
Sending an email attachment via powermailpdf does not work

### ISSUE THREAD

**Issue by sypets** [undkonsorten/powermailpdf#1]
Thank you for providing this useful extension.

However the extension will not send an email attachment. Everything else works, the email is sent, the pdf is generated, the download link is correct.

I will supply a pull request as a suggestion for a fix. 

**TYPO3 : 7.6.23
powermail: 3.22.1**

(I'm aware that TYPO3 7 and powermail 3 is  is not officially supported, but everything else works very well and I think you could bump up the supported versions)

**TypoScript constants:**

```
plugin.tx_powermailpdf.settings.enablePowermailPdf = 1
plugin.tx_powermailpdf.settings.sourceFile = fileadmin/templates/ext/powermailpdf/template-fdf.pdf
plugin.tx_powermail.settings.receiver.attachment = 1
plugin.tx_powermail.settings.sender.attachment = 1

```
**TypoScript setup:**

```
plugin.tx_powermailpdf {
    settings {
       fieldMap{
          
          # mapping ...
          name = name
          # etc. 
       }
      email.attachFile = 1
  }
}

```

**Comment by Starkmann** [comment]
Is tis is fixed with your pull request? You do you still have the problem?

**Comment by Starkmann** [comment]
There are also new version available including your pull request

**Comment by sypets** [comment]
I am right in the middle of something, but I will test your latest version with TYPO3 8 soon.

**Comment by sypets** [comment]
I will close this now, do some testing and add issues if I find something.
