### ISSUE TITLE
TYPO3 version 11 support

### ISSUE THREAD

**Issue by outdoorsman** [undkonsorten/powermailpdf#13]
I'm looking to use this extension but would like to be upgrading to TYPO3 version 11 and beyond at some point. Just curious if that's in the works already... etc. :) I see you made some somewhat recent commits, which I didn't notice at first, so seems like things are still being maintained?

**Comment by Starkmann** [comment]
Yes the extension is sill maintained, there is no progress in updating on 11, because we don't need that at the moment.
You are very welcome in updating to 11, if you do so i would recommend to use rector (https://github.com/sabbelasichon/typo3-rector) that makes it easier.

**Comment by outdoorsman** [comment]
Thanks for the tip on `typo3-rector`, I didn't know about that tool before and it looks helpful. I'm in the same boat as you as I'm currently using TYPO3 10, but will be needing to upgrade to TYPO3 11 relatively soon... probably also like you ha ha.

**Comment by outdoorsman** [comment]
Thank you so much for the 4.0.0 release... yay!
