### ISSUE TITLE
Undeclared arguments passed to ViewHelper Undkonsorten\Powermailpdf\ViewHelpers\Misc\VariablesViewHelper: mail

### ISSUE THREAD

**Issue by outdoorsman** [undkonsorten/powermailpdf#14]
In TYPO3 9.5 using `powermail` with `powermailpdf` I'm getting the following error when submitting a form... 

```
Undeclared arguments passed to ViewHelper Undkonsorten\Powermailpdf\ViewHelpers\Misc\VariablesViewHelper: mail.
```

It appears that it's complaining about _mail_ but I don't know what to do about it. I've included the static templates for `powermail` followed by `powermailpdf` in the main TS template and see below for the mapping part of `powermailpdf`. I also added `{downloadLink}` in the RTE area for the receiver in the `powermail` content element and have email addresses entered there as well for the Receiver's Email and Sender's Email.

The only place I found the word _mail_ in the docs was on **[this page](https://docs.typo3.org/typo3cms/extensions/powermailpdf/stable/Administration/Index.html)**, but it appears I don't need to do that since I'm using a `powermail` version greater than 3 right?

## Relevant packages

* [typo3/cms-core](https://packagist.org/packages/typo3/cms-core) 9.5.31
* [templavoilaplus/templavoilaplus](https://packagist.org/packages/templavoilaplus/templavoilaplus) 7.3.6
* [in2code/powermail](https://packagist.org/packages/in2code/powermail) 6.2.0
* [undkonsorten/powermailpdf](https://packagist.org/packages/undkonsorten/powermailpdf) 2.4.5
* [tmw/fpdm](https://packagist.org/packages/tmw/fpdm) 2.9.2

_PS: I also posted this [same question on StackOverflow](https://stackoverflow.com/questions/72034417/undeclared-arguments-passed-to-viewhelper-undkonsorten-powermailpdf-viewhelpers)._

## TypoScript I'm using

```
plugin.tx_powermailpdf {
    settings {
        enablePowermailPdf = 1
        showDownloadLink = 1
        email.attachFile = 1
        filelink {
            jumpurl = 1
            jumpurl.secure = 1
            jumpurl.secure.mimeTypes = pdf=application/pdf
            icon = 1
            icon_link = 1
        }
        sourceFile = EXT:rapidfyre_estreetdrivingschool/Resources/Public/Forms/Student_Training_Record.pdf
        fieldMap{
            # Note the format is... pdfField = PowermailField
            name = studentsname
            address = address
            city = city
            state = state
            zip = zip
            gender = gender
            home_number = homephone
            alternate_number = alternatephone
            student_cell = studentsphone
            student_email = studentsemail
            parent_name = parentsname
            parent_email = parentsemail
            high_school = highschool
            birth_date = dateofbirth
            permit_number = permitorid
            class = class

            # Hidden fields
            orientation = orientation
        }
    }
}
```

## Image of the first part of the error trace

<img width="1158" alt="2022-04-26_22-14-09" src="https://user-images.githubusercontent.com/3075533/165445587-a4dc6ade-a3df-41ba-809b-b922e389ce69.png">

**Comment by r12r** [comment]
@outdoorsman 
I run in the same trouble in a similar setup.
I fixed it by replace the file "Classes/ViewHelpers/Misc/VariablesViewHelper.php" by a newer version:
https://github.com/undkonsorten/powermailpdf/blob/3.0.1/Classes/ViewHelpers/Misc/VariablesViewHelper.php

**Comment by Starkmann** [comment]
Seems to be fixed.
