### ISSUE TITLE
Possibility to save generated PDFs to filesystem?

### ISSUE THREAD

**Issue by ness2828** [undkonsorten/powermailpdf#16]
HI there,

is it possible to save generated PDF files to a specific folder e.g. fileadmin/documents? 

Kind regards 
Ness

**Comment by Starkmann** [comment]
This is done by default.
There is a typoscript setting for that:
```
target{
    # cat=plugin.tx_powermailpdf/settings; type=string; label=Target pdf:Format StoragePid:Folder
    pdf = 1:powermailpdf
}
```

So fileadmin/powermailpdf is default.
