### ISSUE TITLE
TYPO3 v11 Upgrade

### ISSUE THREAD

**Issue by sypets** [undkonsorten/powermailpdf#19]
* no change: Signal Slot Dispatcher is deprecated in v11, but is still used in powermail 10.4.1 - so it should remain
  * https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/Events/SignalsSlots/Index.html

-------

* [x]  ResourceFactory::getInstance() is deprecated in v10
  * https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.3/Deprecation-90260-ResourceFactorygetInstancePseudo-factory.html

> replace with constructor injection via Dependency Injection if possible, or use GeneralUtility::makeInstance(ResourceFactory::class) instead.

-------

* later: Extbase ObjectManager is deprecated in v11 - if current version should still work in v10, do not remove, but can be done in next step as breaking change with new major version
  *  https://docs.typo3.org/c/typo3/cms-core/11.5/en-us/Changelog/11.4/Deprecation-94619-ExtbaseObjectManager.html

-------

* [x] Call to undefined method In2code\Powermail\Utility\ObjectUtility::getObjectManager() in /var/www/site-uol11/htdocs/typo3conf/ext/powermailpdf/Classes/ViewHelpers/Misc/VariablesViewHelper.php line 122
   * use dependency injection or GeneralUtility::makeInstance to initiate the objects

-------

I think changes can be made so extension still runs with v10 and v11 but it is not possible to get rid of all deprecations (because e.g. Signal / Slot still used in powermail). 

I will create a PR.

**Comment by Starkmann** [comment]
First of all thanks for the detailed PR. (again ;-))

I did some testing today

- [x] TYPO3 10.4 with powermail 8

- [ ]  TYPO3 11.5 with powermail 9
The PDF file is generated but the link on the submit page is not rendered correctly. I'm not sure if this is a problem of my testing environment or not. Did you tested or experienced this behavior as well? 
![image](https://user-images.githubusercontent.com/3470953/179547882-a48ec98a-ca3b-4036-aca2-eee1cfd4dfe3.png)

- [ ]  TYPO3 11.5 with powermail 10
Not tested yet.

**Comment by Starkmann** [comment]
Seems like we can not pass html to an answer anymore. TYPO3 11.5 is escaping that.
Using `{escaping off}` in `typo3conf/ext/powermail/Resources/Private/Partials/PowermailAll/Web.html` fixes that issue but that is not a good solution.
