### ISSUE TITLE
Wrong TypoScript object path

### ISSUE THREAD

**Issue by responseinformationsdesign** [undkonsorten/powermailpdf#7]
The TypoScript object path in "setup.text" and the manual for jumpurl is wrong.

It has to be 

`plugin.tx_powermailpdf.settings.filelink.typolinkConfiguration.jumpurl `

instead of

`plugin.tx_powermailpdf.settings.filelink.jumpurl `

**Comment by Starkmann** [comment]
Thanks for the report and sorry for the lat answer.

The new version i release today no longer needs filelink configuration.
