### ISSUE TITLE
Support latest powermail versions

### ISSUE THREAD

**Issue by georgringer** [undkonsorten/powermailpdf#9]
would be cool to support powermail 7x

**Comment by stephangrass** [comment]
And TYPO3 10 and powermail 8x

**Comment by Starkmann** [comment]
Yes the plan is to do so, the problem is that powermail has so many major versions  that it is hard to keep up with all of them.
I mean for typo3 8 they have 6 major version, which are sometimes incompatible with powermailpdf because of architecture or slot changes.

**Comment by Starkmann** [comment]
I released a new version today:
https://github.com/undkonsorten/powermailpdf/releases/tag/3.0.0

This version supports typo3 10 and powermail 8, only. I mentioned the reasons for this decision before.

If there is major interest i might find the time to backport this release to powermail 7 and typo3 9.5
